version: '3.8'

services:
  md2googleslides:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-}
        - VCS_REF=${VCS_REF:-}
        - VERSION=${VERSION:-0.5.3}
    image: md2googleslides:latest
    container_name: md2googleslides
    volumes:
      # Monter le répertoire de travail pour les fichiers d'entrée/sortie
      - ./workspace:/workspace
      # Monter le répertoire de credentials Google (optionnel)
      - ./credentials:/home/md2gslides/.md2googleslides:ro
    working_dir: /workspace
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
    # Commande par défaut - peut être surchargée
    command: ["--help"]
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
  # Service pour le développement et les tests
  md2googleslides-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: md2googleslides:dev
    container_name: md2googleslides-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: ["npm", "test"]
    profiles:
      - dev

  # Service pour les tests
  md2googleslides-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: md2googleslides:test
    container_name: md2googleslides-test
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=test
    command: ["npm", "test"]
    profiles:
      - test

# Réseau par défaut
networks:
  default:
    name: md2googleslides-network

# Volumes pour la persistance des données
volumes:
  workspace:
    driver: local
  credentials:
    driver: local
