version: '3.8'

services:
  md2googleslides:
    build:
      context: .
      dockerfile: Dockerfile
    image: md2googleslides:latest
    container_name: md2slides
    ports:
      - "3000:3000"
    volumes:
      # Monter le répertoire de travail pour les fichiers d'entrée/sortie
      - ./workspace:/workspace
      # 🔧 CRITIQUE: Supprimer :ro pour permettre l'écriture des tokens OAuth
      - ./credentials:/home/md2gslides/.md2googleslides
      - /tmp:/tmp
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIRECT_URI=https://n8n-ivayh-u36210.vm.elestio.app/oauth/callback
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - md2slides_network

  # Service pour le développement et les tests
  md2googleslides-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: md2googleslides:dev
    container_name: md2googleslides-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: ["npm", "test"]
    profiles:
      - dev

  # Service pour les tests
  md2googleslides-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: md2googleslides:test
    container_name: md2googleslides-test
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=test
    command: ["npm", "test"]
    profiles:
      - test

# Réseau par défaut
networks:
  md2slides_network:
    driver: bridge

# Volumes pour la persistance des données
volumes:
  workspace:
    driver: local
  credentials:
    driver: local
